### PR TITLE
Update babel to support newer syntax

### PR DESCRIPTION
**Pull request by wdoug**
# Summary

Currently, if I try to run the string extractor from this project it fails to parse any newer syntax that the current versions of babel in this project don't support. One specific example is that it fails to parse TypeScript 3.8's [`import type` syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export). This results in a `BABEL_PARSE_ERROR` being logged and that file failing to successfully extract strings to the `resources.tsx` file.

## Test Plan

After upgrading these babel dependencies, I ran the string extractor (`yarn start --src=FILES`) on a bunch of different files and different selections of files and it had no issue. I also ran the codemod on a bunch of files and that continued to work as expected.

### What's required for testing (prerequisites)?

Pulling this branch, installing, and running it on some code

### What are the steps to reproduce (after prerequisites)?

You can reproduce the original bug by running the `master` version of this project on code that has `import type Foo from 'bar';` in the file.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |

## Checklist

- [ ] ~~I have tested this on a device and a simulator~~ - n/a
- [ ] ~~I added the documentation in `README.md`~~ - n/a
- [ ] I mentioned this change in `CHANGELOG.md` - is there a changelog for this project?
- [ ] I updated the typed files (TS and Flow) - I did not. I briefly tried running at least the typescript type checker on the codebase, but I ran into some pre-existing issues so I wasn't sure what to do about that 🤷 
- [ ] ~~I added a sample use of the API in the example project (`example/App.js`)~~ - n/a

### CODE REVIEW

**Comment by sibelius** [comment]
Can you also bump package.json?

**Comment by wdoug** [comment]
I bumped the patch version. Let me know if there is anything else

**Comment by sibelius** [comment]
You should the dependencies and devDependencies

Use yarn outdated or yarn upgrade

**Comment by sibelius** [comment]
the bump should be like this https://github.com/sibelius/ast-i18n/pull/78

that pr is breaking a few tests, feel free to try to fix them

or just upgrade the babel packages on package.json

**Comment by wdoug** [comment]
> the bump should be like this #78

When I did that it broke things so I just used `yarn upgrade --scope @babel` instead, which fixed the problem that I was having and didn't break tests.

My personal request would be to merge this first to address that one specific issue and then do a follow-up that does a more thorough update of versions like you have in #78 when there is time to investigate why things are breaking there. What do you think?

**Comment by sibelius** [comment]
let's try that, tks

**Comment by wdoug** [comment]
Thanks!

**Pull request merged**
